baseURL = "https://example.com"
languageCode = "en-us"
title = "CodeScenery"
pygmentsstyle = "monokai"
metaDataFormat = "toml"
paginate = 6

[[module.imports]]
path = "github.com/forestryio/hugo-theme-novela"

[social]
twitter = "#"
github = "#"
instagram = "#"
linkedin = "#"
dribbble = "#"
youtube = "#"

[taxonomies]
author = "authors"
