baseURL = "/"
languageCode = "en-us"
title = "CodeScenery"
pygmentsstyle = "monokai"
metaDataFormat = "toml"
paginate = 6

[[module.imports]]
path = "github.com/carsonip/hugo-theme-minos"

[social]
twitter = "#"
github = "#"
instagram = "#"
linkedin = "#"
dribbble = "#"
youtube = "#"

[taxonomies]
author = "authors"

[params]
    customCss = ["css/codescenery.css"]
